modLoader="javafml"
loaderVersion="[39,)"
license="All Rights Reserved to Lightworks Studios"
issueTrackerURL="https://change.me.to.your.issue.tracker.example.invalid/"

[[mods]]
modId="mysticalflames"
version="0.1.7"
displayName="Mystical Flames"
#updateJSONURL=""
displayURL="https://gemeersh.wixsite.com/mystical-flames"
logoFile="logo.png"
credits="This mod wouldn't have been possible without our amazing Patreon Supporters, without them this mod wouldn't have started, or been able to progress"
authors="Ersh Gem, Emerald Hunter, Dan, MidnightPony, ShadowRogueG, BloodViper2020, JurassicAlien, Aurum, MidnightPony, FuriadaNoite, Shinyju, Pharosite" #optional
description='''
The Mystical Flames mod is a Minecraft mod that adds a variety of dragons and mythical beasts for you to tame, train, and discover for yourself. Tame a devastating wyvern, train a graceful phoenix, defend dragon-kind from the foul dragon hunters, soar through the world on the back of your faithful companion... Your Adventure Awaits!!'''

[[dependencies.mysticalflames]]
    modId="forge"
    mandatory=true
    versionRange="[39,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.mysticalflames]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.1,1.19)"
    ordering="NONE"
    side="BOTH"
